# Change these first
owner: Halibuben # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

check-cert-expiry: 14

sites:
  - name: Community website
    url: https://tvoyaridna.com/health
    expectedStatusCodes:
      - 200
  - name: Streaming API
    url: https://tvoyaridna.com/api/v1/streaming/health
    expectedStatusCodes:
      - 200
  - name: Public API
    url: https://tvoyaridna.com/api/v2/instance
    expectedStatusCodes:
      - 200
  - name: Media storage
    url: https://assets.tvoyaridna.com/health.txt
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "OK"
  - name: SMTP Submission
    url: mail.copykor.in.ua
    port: 587
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tvoyaridna.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Tvoya Ridna Status Page
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Return
      href: https://tvoyaridna.com
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
